# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Phone Number (Optional) '),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/no-pic-uploaded.png', upload_to='profile_picture/', verbose_name='Profile Picture (Optional) '),
        ),
    ]
