# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='contest_description',
            new_name='contest_info',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='contest_duration',
            new_name='posted_date',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_description',
            new_name='coupon_info',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_validity',
            new_name='posted_date',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='offer_date',
            new_name='posted_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_date',
            new_name='posted_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_duration',
        ),
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_ends',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_madedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_zip',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
