# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0002_auto_20170227_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_info',
            field=models.TextField(null=True),
        ),
    ]
