# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_friend_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
    ]
